name: Envio Reporte Diario 5:30PM

on:
  schedule:
    - cron: '30 21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # ESTA ES LA LÍNEA CLAVE QUE DEBES AÑADIR:
    environment: Dexter  

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install pandas sqlalchemy psycopg2-binary openpyxl

      - name: Ejecutar script de envío
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_JEFE: ${{ secrets.EMAIL_JEFE }}
        run: python correo_automatico.py
