[theme]
# Un color burdeos o rojo oscuro, muy profesional
primaryColor="#9a3e3e"

# Fondo principal en un color "hueso" o beige muy claro
backgroundColor="#f9f9f9"

# Sidebar y contenedores en blanco
secondaryBackgroundColor="#ffffff"

# Texto en un azul oscuro para un contraste limpio y profesional
textColor="#0a2a4a" # Este es un azul oscuro, casi marino

font="sans serif"
